name: Sync LeetCode Solutions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # Runs daily automatically

jobs:
  build:
    name: Sync LeetCode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync LeetCode Solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.CSRFTOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'LeetCode'
